<a href="https://colab.research.google.com/github/bobbercheng/ventilator-pressure-prediction/blob/master/ventilator_pressure_transformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#!pip install pandas==1.3.2

Collecting pandas==1.3.2
  Downloading pandas-1.3.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.3 MB)
     |████████████████████████████████| 11.3 MB 4.6 MB/s
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas==1.3.2) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas==1.3.2) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas==1.3.2) (1.19.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas==1.3.2) (1.15.0)
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 1.1.5
    Uninstalling pandas-1.1.5:
      Successfully uninstalled pandas-1.1.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas~=1.1.0; python_version >= "3.0", but you have pandas 1.3.2 which is incompatible.
Successfully installed pandas-1.3.2

In [1]:
from google.colab import drive
drive.mount("/gdrive", force_remount=True)

Mounted at /gdrive

In [2]:
!pip install kaggle
!mkdir /root/.kaggle
!cp /gdrive/MyDrive/ventilator-pressure-prediction/kaggle.json /root/.kaggle
!kaggle competitions download -c ventilator-pressure-prediction
!mkdir -p /kaggle/input/ventilator-pressure-prediction
!unzip '*.zip' -d /kaggle/input/ventilator-pressure-prediction
!ls /kaggle/input/ventilator-pressure-prediction

Requirement already satisfied: kaggle in /usr/local/lib/python3.7/dist-packages (1.5.12)
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from kaggle) (2021.5.30)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.7/dist-packages (from kaggle) (1.15.0)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from kaggle) (2.23.0)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.7/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.7/dist-packages (from kaggle) (1.24.3)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.7/dist-packages (from kaggle) (5.0.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from kaggle) (4.62.3)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.7/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->kaggle) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->kaggle) (3.0.4)
Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.4)
Downloading test.csv.zip to /content
 93% 70.0M/75.4M [00:00<00:00, 142MB/s]
100% 75.4M/75.4M [00:00<00:00, 154MB/s]
Downloading train.csv.zip to /content
 97% 135M/139M [00:00<00:00, 195MB/s]
100% 139M/139M [00:00<00:00, 191MB/s]
Downloading sample_submission.csv.zip to /content
  0% 0.00/8.50M [00:00<?, ?B/s]
100% 8.50M/8.50M [00:00<00:00, 78.2MB/s]
Archive:  sample_submission.csv.zip
  inflating: /kaggle/input/ventilator-pressure-prediction/sample_submission.csv

Archive:  test.csv.zip
  inflating: /kaggle/input/ventilator-pressure-prediction/test.csv

Archive:  train.csv.zip
  inflating: /kaggle/input/ventilator-pressure-prediction/train.csv

3 archives were successfully processed.
sample_submission.csv  test.csv  train.csv

In [3]:
import numpy as np
import pandas as pd

# import optuna

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.callbacks import LearningRateScheduler, ReduceLROnPlateau
from tensorflow.keras.optimizers.schedules import ExponentialDecay

from sklearn.metrics import mean_absolute_error as mae
from sklearn.preprocessing import RobustScaler, normalize
from sklearn.model_selection import train_test_split, GroupKFold, KFold

from IPython.display import display

In [4]:
DEBUG = False

train = pd.read_csv('/kaggle/input/ventilator-pressure-prediction/train.csv')
test = pd.read_csv('/kaggle/input/ventilator-pressure-prediction/test.csv')
submission = pd.read_csv('/kaggle/input/ventilator-pressure-prediction/sample_submission.csv')

if DEBUG:
    train = train[:80*1000]

In [5]:
def add_feats(train):
    # # rewritten calculation of lag features from this notebook: https://www.kaggle.com/patrick0302/add-lag-u-in-as-new-feat
# # some of ideas from this notebook: https://www.kaggle.com/mst8823/google-brain-lightgbm-baseline
    # train[["15_out_mean"]] = train.groupby('breath_id')['u_out'].rolling(window=15,min_periods=1).agg({"15_out_mean":"mean"}).reset_index(level=0,drop=True)
    train['last_value_u_in'] = train.groupby('breath_id')['u_in'].transform('last')
    train['u_in_lag1'] = train.groupby('breath_id')['u_in'].shift(1)
    train['u_out_lag1'] = train.groupby('breath_id')['u_out'].shift(1)
    train['u_in_lag_back1'] = train.groupby('breath_id')['u_in'].shift(-1)
    train['u_out_lag_back1'] = train.groupby('breath_id')['u_out'].shift(-1)
    train['u_in_lag2'] = train.groupby('breath_id')['u_in'].shift(2)
    train['u_out_lag2'] = train.groupby('breath_id')['u_out'].shift(2)
    train['u_in_lag3'] = train.groupby('breath_id')['u_in'].shift(3)
    train['u_out_lag3'] = train.groupby('breath_id')['u_out'].shift(3)
    train['u_in_lag_back2'] = train.groupby('breath_id')['u_in'].shift(-2)
    train['u_out_lag_back2'] = train.groupby('breath_id')['u_out'].shift(-2)
    train['u_in_lag_back3'] = train.groupby('breath_id')['u_in'].shift(-3)
    train['u_out_lag_back3'] = train.groupby('breath_id')['u_out'].shift(-3)
    train['u_in_lag_back10'] = train.groupby('breath_id')['u_in'].shift(-10)
    train['u_out_lag_back10'] = train.groupby('breath_id')['u_out'].shift(-10)

    train['u_in_first'] = train.groupby('breath_id')['u_in'].first()
    train['u_out_first'] = train.groupby('breath_id')['u_out'].first()

    ## time since last step
    train['time_step_diff'] = train.groupby('breath_id')['time_step'].diff().fillna(0)
    ### rolling window ts feats
    train['ewm_u_in_mean'] = train.groupby('breath_id')['u_in'].ewm(halflife=9).mean().reset_index(level=0,drop=True)
    train['ewm_u_in_std'] = train.groupby('breath_id')['u_in'].ewm(halflife=10).std().reset_index(level=0,drop=True) ## could add covar?
    train['ewm_u_in_corr'] = train.groupby('breath_id')['u_in'].ewm(halflife=15).corr().reset_index(level=0,drop=True) # self umin corr
    # train['ewm_u_in_corr'] = train.groupby('breath_id')['u_in'].ewm(halflife=6).corr(train.groupby('breath_id')["u_out"]).reset_index(level=0,drop=True) # corr with u_out # error
    ## rolling window of 15 periods
    train[["15_in_sum","15_in_min","15_in_max","15_in_mean","15_out_std"]] = train.groupby('breath_id')['u_in'].rolling(window=15,min_periods=1).agg({"15_in_sum":"sum","15_in_min":"min","15_in_max":"max","15_in_mean":"mean","15_in_std":"std"}).reset_index(level=0,drop=True)
#     train[["45_in_sum","45_in_min","45_in_max","45_in_mean","45_out_std"]] = train.groupby('breath_id')['u_in'].rolling(window=45,min_periods=1).agg({"45_in_sum":"sum","45_in_min":"min","45_in_max":"max","45_in_mean":"mean","45_in_std":"std"}).reset_index(level=0,drop=True)
    train[["45_in_sum","45_in_min","45_in_max","45_in_mean","45_out_std"]] = train.groupby('breath_id')['u_in'].rolling(window=45,min_periods=1).agg({"45_in_sum":"sum","45_in_min":"min","45_in_max":"max","45_in_mean":"mean","45_in_std":"std"}).reset_index(level=0,drop=True)

    train[["15_out_mean"]] = train.groupby('breath_id')['u_out'].rolling(window=15,min_periods=1).agg({"15_out_mean":"mean"}).reset_index(level=0,drop=True)

    print(train.shape[0])
    display(train)
    train = train.fillna(0) # ORIG

    # max, min, mean value of u_in and u_out for each breath
    train['breath_id__u_in__max'] = train.groupby(['breath_id'])['u_in'].transform('max')
    train['breath_id__u_out__max'] = train.groupby(['breath_id'])['u_out'].transform('max')

    train['breath_id__u_out__mean'] =train.groupby(['breath_id'])['u_out'].mean()
    train['breath_id__u_in__mean'] =train.groupby(['breath_id'])['u_in'].mean()

    train['breath_id__u_in__min'] = train.groupby(['breath_id'])['u_in'].transform('min')
    train['breath_id__u_out__min'] = train.groupby(['breath_id'])['u_out'].transform('min')

    train['u_in_first'] = train.groupby(['breath_id'])['u_in'].transform('first')
    train['u_in_last'] = train.groupby(['breath_id'])['u_in'].transform('last')

    train['R_div_C'] = train["R"].div(train["C"])

    # difference between consequitive values
    train['R__C'] = train["R"].astype(str) + '__' + train["C"].astype(str)
    train['u_in_diff1'] = train['u_in'] - train['u_in_lag1']
    train['u_out_diff1'] = train['u_out'] - train['u_out_lag1']
    train['u_in_diff2'] = train['u_in'] - train['u_in_lag2']
    train['u_out_diff2'] = train['u_out'] - train['u_out_lag2']
    train['u_in_diff3'] = train['u_in'] - train['u_in_lag3']
    train['u_out_diff3'] = train['u_out'] - train['u_out_lag3']
    ## diff between last 2 steps
    train['u_in_diff_1_2'] = train['u_in_lag1'] - train['u_in_lag2']
    train['u_out_diff_1_2'] = train['u_out_lag1'] - train['u_out_lag2']
    train['u_in_lagback_diff_1_2'] = train['u_in_lag_back1'] - train['u_in_lag_back2']
    train['u_out_lagback_diff_1_2'] = train['u_out_lag_back1'] - train['u_out_lag_back2']

    train['u_in_lagback_diff1'] = train['u_in'] - train['u_in_lag_back1']
    train['u_out_lagback_diff1'] = train['u_out'] - train['u_out_lag_back1']
    train['u_in_lagback_diff2'] = train['u_in'] - train['u_in_lag_back2']
    train['u_out_lagback_diff2'] = train['u_out'] - train['u_out_lag_back2']

    # from here: https://www.kaggle.com/yasufuminakama/ventilator-pressure-lstm-starter
    train.loc[train['time_step'] == 0, 'u_in_diff'] = 0
    train.loc[train['time_step'] == 0, 'u_out_diff'] = 0

    # difference between the current value of u_in and the max value within the breath
    train['breath_id__u_in__diffmax'] = train.groupby(['breath_id'])['u_in'].transform('max') - train['u_in']
    train['breath_id__u_in__diffmean'] = train.groupby(['breath_id'])['u_in'].transform('mean') - train['u_in']

    print("before OHE")
    display(train)

    # OHE
    train = train.merge(pd.get_dummies(train['R'], prefix='R'), left_index=True, right_index=True).drop(['R'], axis=1)
    train = train.merge(pd.get_dummies(train['C'], prefix='C'), left_index=True, right_index=True).drop(['C'], axis=1)
    train = train.merge(pd.get_dummies(train['R__C'], prefix='R__C'), left_index=True, right_index=True).drop(['R__C'], axis=1)

    # https://www.kaggle.com/c/ventilator-pressure-prediction/discussion/273974
    train['u_in_cumsum'] = train.groupby(['breath_id'])['u_in'].cumsum()
    train['time_step_cumsum'] = train.groupby(['breath_id'])['time_step'].cumsum()

    # feature by u in or out (ideally - make 2 sep columns for each state) # dan
    train['u_in_partition_out_sum'] = train.groupby(['breath_id',"u_out"])['u_in'].transform("sum")

    train = train.fillna(0) # add for consistency with how test is done - dan

    return train

train = add_feats(train)
test = add_feats(test)

6036000

              id  breath_id   R  ...  45_in_mean  45_out_std  15_out_mean
0              1          1  20  ...    0.083334         NaN          0.0
1              2          1  20  ...    9.233188   12.939847          0.0
2              3          1  20  ...   13.658551   11.936136          0.0
3              4          1  20  ...   15.946119   10.766279          0.0
4              5          1  20  ...   17.828065   10.229525          0.0
...          ...        ...  ..  ...         ...         ...          ...
6035995  6035996     125749  50  ...    3.132079    4.277354          1.0
6035996  6035997     125749  50  ...    3.165156    4.258295          1.0
6035997  6035998     125749  50  ...    2.890898    3.936430          1.0
6035998  6035999     125749  50  ...    2.607671    3.557961          1.0
6035999  6036000     125749  50  ...    2.361694    3.221585          1.0

[6036000 rows x 40 columns]

before OHE

              id  ...  breath_id__u_in__diffmean
0              1  ...                  10.062673
1              2  ...                  -8.237035
2              3  ...                 -12.363271
3              4  ...                 -12.662816
4              5  ...                 -15.209844
...          ...  ...                        ...
6035995  6035996  ...                   3.421689
6035996  6035997  ...                   3.422905
6035997  6035998  ...                   3.352424
6035998  6035999  ...                   3.638739
6035999  6036000  ...                   3.428663

[6036000 rows x 67 columns]

4024000

              id  breath_id   R  ...  45_in_mean  45_out_std  15_out_mean
0              1          0   5  ...    0.000000         NaN          0.0
1              2          0   5  ...    3.757523    5.313940          0.0
2              3          0   5  ...    7.388907    7.326652          0.0
3              4          0   5  ...   10.849333    9.147936          0.0
4              5          0   5  ...   13.943657   10.518450          0.0
...          ...        ...  ..  ...         ...         ...          ...
4023995  4023996     125748  20  ...    2.794529    2.152980          1.0
4023996  4023997     125748  20  ...    2.905101    2.133884          1.0
4023997  4023998     125748  20  ...    3.015755    2.108773          1.0
4023998  4023999     125748  20  ...    3.126481    2.077404          1.0
4023999  4024000     125748  20  ...    3.237267    2.039469          1.0

[4024000 rows x 39 columns]

before OHE

              id  ...  breath_id__u_in__diffmean
0              1  ...                   9.327338
1              2  ...                   1.812292
2              3  ...                  -5.324338
3              4  ...                 -11.903272
4              5  ...                 -16.993619
...          ...  ...                        ...
4023995  4023996  ...                  -2.288270
4023996  4023997  ...                  -2.292733
4023997  4023998  ...                  -2.296492
4023998  4023999  ...                  -2.299672
4023999  4024000  ...                  -2.302397

[4024000 rows x 66 columns]

In [6]:
train.head()

   id  breath_id  ...  time_step_cumsum  u_in_partition_out_sum
0   1          1  ...          0.000000              663.594727
1   2          1  ...          0.033652              663.594727
2   3          1  ...          0.101167              663.594727
3   4          1  ...          0.202709              663.594727
4   5          1  ...          0.338464              663.594727

[5 rows x 82 columns]

In [7]:
train.shape

(6036000, 82)

In [8]:
targets = train[['pressure']].to_numpy().reshape(-1, 80)
#u_outs = train[['u_out']].to_numpy().reshape(-1, 80)
train.drop(['pressure', 'id', 'breath_id'], axis=1, inplace=True)
test = test.drop(['id', 'breath_id'], axis=1)

In [9]:
RS = RobustScaler()
train = RS.fit_transform(train)
test = RS.transform(test)

In [10]:
train = train.reshape(-1, 80, train.shape[-1])
test = test.reshape(-1, 80, train.shape[-1])

In [11]:
def GBVPP_loss(y_true, y_pred, cols = 80):
    u_out = y_true[:, cols: ]
    y = y_true[:, :cols ]

    w = 1 - u_out
    mae = w * tf.abs(y - y_pred)
    return tf.reduce_sum(mae, axis=-1) / tf.reduce_sum(w, axis=-1)

In [12]:
from tensorflow.keras.layers import Layer
from tensorflow.keras import backend as K

class Attention(Layer):
    
    def __init__(self, return_sequences=True):
        self.return_sequences = return_sequences
        super(Attention,self).__init__()
        
    def build(self, input_shape):
        
        self.W=self.add_weight(name="att_weight", shape=(input_shape[-1],1),
                               initializer="normal")
        self.b=self.add_weight(name="att_bias", shape=(input_shape[1],1),
                               initializer="zeros")
        
        super(Attention,self).build(input_shape)
        
    def call(self, x):
        
        e = K.tanh(K.dot(x,self.W)+self.b)
        a = K.softmax(e, axis=1)
        output = x*a
        
        if self.return_sequences:
            return output
        
        return K.sum(output, axis=1)

    def get_config(self):
        return super(Attention, self).get_config()

In [13]:
def get_cnn_model(train):
  inputs = keras.layers.Input(shape=train.shape[-2:])
  X = inputs

  X = keras.layers.Conv1D(filters=2048, kernel_size=3, activation='relu')(X)
  X = keras.layers.BatchNormalization()(X)
  X = keras.layers.Conv1D(filters=2048, kernel_size=3, activation='relu')(X)
  X = keras.layers.BatchNormalization()(X)
  X = keras.layers.AveragePooling1D(pool_size=2)(X)

  X = Attention(return_sequences=True)(X)

  X = keras.layers.Conv1D(filters=1024, kernel_size=3, activation='relu')(X)
  X = keras.layers.BatchNormalization()(X)
  X = keras.layers.Conv1D(filters=1024, kernel_size=3, activation='relu')(X)
  X = keras.layers.BatchNormalization()(X)
  X = keras.layers.AveragePooling1D(pool_size=2)(X)

  X = Attention(return_sequences=True)(X)


  X = keras.layers.Conv1D(filters=512, kernel_size=3, activation='relu')(X)
  X = keras.layers.BatchNormalization()(X)
  X = keras.layers.Conv1D(filters=512, kernel_size=3, activation='relu')(X)
  X = keras.layers.BatchNormalization()(X)
  X = keras.layers.AveragePooling1D(pool_size=2)(X)

  X = Attention(return_sequences=True)(X)

  X = keras.layers.Conv1D(filters=256, kernel_size=3, activation='relu')(X)
  X = keras.layers.BatchNormalization()(X)
  X = keras.layers.Conv1D(filters=256, kernel_size=3, activation='relu')(X)
  X = keras.layers.BatchNormalization()(X)
  X = keras.layers.AveragePooling1D(pool_size=2)(X)

  X = Attention(return_sequences=True)(X)

  X = keras.layers.Flatten()(X) #256

  input_X = keras.layers.Flatten()(inputs)
  input_X = keras.layers.Dense(512, activation='selu', kernel_initializer='lecun_normal')(input_X)
  input_X = keras.layers.BatchNormalization()(input_X)
  input_X = keras.layers.Dense(256, activation='selu', kernel_initializer='lecun_normal')(input_X)
  input_X = keras.layers.BatchNormalization()(input_X) #256

  X = keras.layers.Concatenate()([X, input_X])

  X = keras.layers.Dense(256, activation='selu', kernel_initializer='lecun_normal')(X)
  X = keras.layers.BatchNormalization()(X)
  outputs = keras.layers.Dense(80)(X)
  model  = keras.Model(inputs=inputs, outputs=outputs)
  model.summary()
  return model

In [14]:
from tensorflow.keras import layers
from tensorflow import keras

In [15]:
def transformer_encoder(inputs, head_size, num_heads, ff_dim, dropout=0):
    # Normalization and Attention
    x = layers.LayerNormalization(epsilon=1e-6)(inputs)
    x = layers.MultiHeadAttention(
        key_dim=head_size, num_heads=num_heads, dropout=dropout
    )(x, x)
    x = layers.Dropout(dropout)(x)
    res = x + inputs

    # Feed Forward Part
    x = layers.LayerNormalization(epsilon=1e-6)(res)
    x = layers.Conv1D(filters=ff_dim, kernel_size=1, activation="relu")(x)
    x = layers.Dropout(dropout)(x)
    x = layers.Conv1D(filters=inputs.shape[-1], kernel_size=1)(x)
    return x + res

In [34]:
def build_transfer_model(
    input_shape,
    head_size=256,
    num_heads=8,
    ff_dim=1024,
    num_transformer_blocks=8,
    mlp_units=[16, 1],
    dropout=0,
    mlp_dropout=0,
):
    inputs = keras.Input(shape=input_shape)
    x = inputs
    for _ in range(num_transformer_blocks):
        x = transformer_encoder(x, head_size, num_heads, ff_dim, dropout)

    x_pool = layers.GlobalAveragePooling1D(data_format="channels_first")(x)
    x_pool = tf.expand_dims(x_pool, -1)

    for dim in mlp_units:
        x = layers.Dense(dim, activation="relu")(x)
        x = layers.Dropout(mlp_dropout)(x)

    outputs = layers.Dense(dim, activation="relu")(x + x_pool)
    model = keras.Model(inputs, outputs)
    model.summary()
    return model

In [26]:
# model = build_transfer_model(train.shape[1:])
# del model

Model: "model_3"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to
==================================================================================================
input_4 (InputLayer)            [(None, 80, 79)]     0
__________________________________________________________________________________________________
layer_normalization_24 (LayerNo (None, 80, 79)       158         input_4[0][0]
__________________________________________________________________________________________________
multi_head_attention_12 (MultiH (None, 80, 79)       326735      layer_normalization_24[0][0]
                                                                 layer_normalization_24[0][0]
__________________________________________________________________________________________________
dropout_30 (Dropout)            (None, 80, 79)       0           multi_head_attention_12[0][0]
__________________________________________________________________________________________________
tf.__operators__.add_26 (TFOpLa (None, 80, 79)       0           dropout_30[0][0]
                                                                 input_4[0][0]
__________________________________________________________________________________________________
layer_normalization_25 (LayerNo (None, 80, 79)       158         tf.__operators__.add_26[0][0]
__________________________________________________________________________________________________
conv1d_24 (Conv1D)              (None, 80, 1024)     81920       layer_normalization_25[0][0]
__________________________________________________________________________________________________
dropout_31 (Dropout)            (None, 80, 1024)     0           conv1d_24[0][0]
__________________________________________________________________________________________________
conv1d_25 (Conv1D)              (None, 80, 79)       80975       dropout_31[0][0]
__________________________________________________________________________________________________
tf.__operators__.add_27 (TFOpLa (None, 80, 79)       0           conv1d_25[0][0]
                                                                 tf.__operators__.add_26[0][0]
__________________________________________________________________________________________________
layer_normalization_26 (LayerNo (None, 80, 79)       158         tf.__operators__.add_27[0][0]
__________________________________________________________________________________________________
multi_head_attention_13 (MultiH (None, 80, 79)       326735      layer_normalization_26[0][0]
                                                                 layer_normalization_26[0][0]
__________________________________________________________________________________________________
dropout_32 (Dropout)            (None, 80, 79)       0           multi_head_attention_13[0][0]
__________________________________________________________________________________________________
tf.__operators__.add_28 (TFOpLa (None, 80, 79)       0           dropout_32[0][0]
                                                                 tf.__operators__.add_27[0][0]
__________________________________________________________________________________________________
layer_normalization_27 (LayerNo (None, 80, 79)       158         tf.__operators__.add_28[0][0]
__________________________________________________________________________________________________
conv1d_26 (Conv1D)              (None, 80, 1024)     81920       layer_normalization_27[0][0]
__________________________________________________________________________________________________
dropout_33 (Dropout)            (None, 80, 1024)     0           conv1d_26[0][0]
__________________________________________________________________________________________________
conv1d_27 (Conv1D)              (None, 80, 79)       80975       dropout_33[0][0]
__________________________________________________________________________________________________
tf.__operators__.add_29 (TFOpLa (None, 80, 79)       0           conv1d_27[0][0]
                                                                 tf.__operators__.add_28[0][0]
__________________________________________________________________________________________________
layer_normalization_28 (LayerNo (None, 80, 79)       158         tf.__operators__.add_29[0][0]
__________________________________________________________________________________________________
multi_head_attention_14 (MultiH (None, 80, 79)       326735      layer_normalization_28[0][0]
                                                                 layer_normalization_28[0][0]
__________________________________________________________________________________________________
dropout_34 (Dropout)            (None, 80, 79)       0           multi_head_attention_14[0][0]
__________________________________________________________________________________________________
tf.__operators__.add_30 (TFOpLa (None, 80, 79)       0           dropout_34[0][0]
                                                                 tf.__operators__.add_29[0][0]
__________________________________________________________________________________________________
layer_normalization_29 (LayerNo (None, 80, 79)       158         tf.__operators__.add_30[0][0]
__________________________________________________________________________________________________
conv1d_28 (Conv1D)              (None, 80, 1024)     81920       layer_normalization_29[0][0]
__________________________________________________________________________________________________
dropout_35 (Dropout)            (None, 80, 1024)     0           conv1d_28[0][0]
__________________________________________________________________________________________________
conv1d_29 (Conv1D)              (None, 80, 79)       80975       dropout_35[0][0]
__________________________________________________________________________________________________
tf.__operators__.add_31 (TFOpLa (None, 80, 79)       0           conv1d_29[0][0]
                                                                 tf.__operators__.add_30[0][0]
__________________________________________________________________________________________________
layer_normalization_30 (LayerNo (None, 80, 79)       158         tf.__operators__.add_31[0][0]
__________________________________________________________________________________________________
multi_head_attention_15 (MultiH (None, 80, 79)       326735      layer_normalization_30[0][0]
                                                                 layer_normalization_30[0][0]
__________________________________________________________________________________________________
dropout_36 (Dropout)            (None, 80, 79)       0           multi_head_attention_15[0][0]
__________________________________________________________________________________________________
tf.__operators__.add_32 (TFOpLa (None, 80, 79)       0           dropout_36[0][0]
                                                                 tf.__operators__.add_31[0][0]
__________________________________________________________________________________________________
layer_normalization_31 (LayerNo (None, 80, 79)       158         tf.__operators__.add_32[0][0]
__________________________________________________________________________________________________
conv1d_30 (Conv1D)              (None, 80, 1024)     81920       layer_normalization_31[0][0]
__________________________________________________________________________________________________
dropout_37 (Dropout)            (None, 80, 1024)     0           conv1d_30[0][0]
__________________________________________________________________________________________________
conv1d_31 (Conv1D)              (None, 80, 79)       80975       dropout_37[0][0]
__________________________________________________________________________________________________
tf.__operators__.add_33 (TFOpLa (None, 80, 79)       0           conv1d_31[0][0]
                                                                 tf.__operators__.add_32[0][0]
__________________________________________________________________________________________________
dense_8 (Dense)                 (None, 80, 16)       1280        tf.__operators__.add_33[0][0]
__________________________________________________________________________________________________
dropout_38 (Dropout)            (None, 80, 16)       0           dense_8[0][0]
__________________________________________________________________________________________________
dense_9 (Dense)                 (None, 80, 1)        17          dropout_38[0][0]
__________________________________________________________________________________________________
global_average_pooling1d_3 (Glo (None, 80)           0           tf.__operators__.add_33[0][0]
__________________________________________________________________________________________________
dropout_39 (Dropout)            (None, 80, 1)        0           dense_9[0][0]
__________________________________________________________________________________________________
tf.expand_dims_4 (TFOpLambda)   (None, 80, 1)        0           global_average_pooling1d_3[0][0]
__________________________________________________________________________________________________
tf.__operators__.add_34 (TFOpLa (None, 80, 1)        0           dropout_39[0][0]
                                                                 tf.expand_dims_4[0][0]
__________________________________________________________________________________________________
dense_10 (Dense)                (None, 80, 1)        2           tf.__operators__.add_34[0][0]
==================================================================================================
Total params: 1,961,083
Trainable params: 1,961,083
Non-trainable params: 0
__________________________________________________________________________________________________

In [ ]:
from tensorflow.keras.optimizers.schedules import ExponentialDecay
EPOCH = 300
BATCH_SIZE = 1024
NUM_FOLDS = 5

# detect and init the TPU
tpu = tf.distribute.cluster_resolver.TPUClusterResolver.connect()

# instantiate a distribution strategy
tpu_strategy = tf.distribute.experimental.TPUStrategy(tpu)

with tpu_strategy.scope():
    kf = KFold(n_splits=NUM_FOLDS, shuffle=True, random_state=2021)
    test_preds = []
    for fold, (train_idx, test_idx) in enumerate(kf.split(train, targets)):
        print('-'*15, '>', f'Fold {fold+1}', '<', '-'*15)
        X_train, X_valid = train[train_idx], train[test_idx]
        y_train, y_valid = targets[train_idx], targets[test_idx]
        #u_out_train, u_out_valid = u_outs[train_idx], u_outs[test_idx]
        
        #model = get_cnn_model(train)
        model = build_transfer_model(train.shape[1:])
        model.compile(optimizer='adam', 
                      # loss=GBVPP_loss,
                      loss="mae"
                      )

        scheduler = ExponentialDecay(1e-3, 40*((len(train)*0.8)/BATCH_SIZE), 1e-5)
        lr = LearningRateScheduler(scheduler, verbose=1)
        # lr = ReduceLROnPlateau(monitor="val_loss", factor=0.75, patience=10, verbose=1)
        es = EarlyStopping(monitor="val_loss", patience=50, verbose=1, mode="min", restore_best_weights=True)
        checkpoint_filepath = f"folds{fold}.hdf5"
        sv = keras.callbacks.ModelCheckpoint(
            checkpoint_filepath, monitor='val_loss', verbose=1, save_best_only=True,
            save_weights_only=False, mode='auto', save_freq='epoch',
            options=None)

        history = model.fit(X_train,
                            y_train,
                            # validation_data=(X_valid, np.append(y_valid, u_out_valid, axis =1)), 
                            validation_data=(X_valid, y_valid), 
                            epochs=EPOCH, 
                            batch_size=1024, 
                            callbacks=[lr,
                                       es,
                                       sv])
    
        test_preds.append(model.predict(test).squeeze().reshape(-1, 1).squeeze())

INFO:tensorflow:Clearing out eager caches

INFO:tensorflow:Clearing out eager caches

WARNING:tensorflow:TPU system grpc://10.43.92.138:8470 has already been initialized. Reinitializing the TPU can cause previously created variables on TPU to be lost.

WARNING:tensorflow:TPU system grpc://10.43.92.138:8470 has already been initialized. Reinitializing the TPU can cause previously created variables on TPU to be lost.

INFO:tensorflow:Initializing the TPU system: grpc://10.43.92.138:8470

INFO:tensorflow:Initializing the TPU system: grpc://10.43.92.138:8470

INFO:tensorflow:Finished initializing TPU system.

INFO:tensorflow:Finished initializing TPU system.
WARNING:absl:`tf.distribute.experimental.TPUStrategy` is deprecated, please use  the non experimental symbol `tf.distribute.TPUStrategy` instead.

INFO:tensorflow:Found TPU system:

INFO:tensorflow:Found TPU system:

INFO:tensorflow:*** Num TPU Cores: 8

INFO:tensorflow:*** Num TPU Cores: 8

INFO:tensorflow:*** Num TPU Workers: 1

INFO:tensorflow:*** Num TPU Workers: 1

INFO:tensorflow:*** Num TPU Cores Per Worker: 8

INFO:tensorflow:*** Num TPU Cores Per Worker: 8

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 0, 0)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 0, 0)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, 0, 0)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, 0, 0)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:0, TPU, 0, 0)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:0, TPU, 0, 0)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:1, TPU, 0, 0)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:1, TPU, 0, 0)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:2, TPU, 0, 0)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:2, TPU, 0, 0)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:3, TPU, 0, 0)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:3, TPU, 0, 0)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:4, TPU, 0, 0)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:4, TPU, 0, 0)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:5, TPU, 0, 0)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:5, TPU, 0, 0)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:6, TPU, 0, 0)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:6, TPU, 0, 0)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:7, TPU, 0, 0)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:7, TPU, 0, 0)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 0, 0)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 0, 0)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 0, 0)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 0, 0)

--------------- > Fold 1 < ---------------
Model: "model_12"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to
==================================================================================================
input_13 (InputLayer)           [(None, 80, 79)]     0
__________________________________________________________________________________________________
layer_normalization_312 (LayerN (None, 80, 79)       158         input_13[0][0]
__________________________________________________________________________________________________
multi_head_attention_156 (Multi (None, 80, 79)       653391      layer_normalization_312[0][0]
                                                                 layer_normalization_312[0][0]
__________________________________________________________________________________________________
dropout_336 (Dropout)           (None, 80, 79)       0           multi_head_attention_156[0][0]
__________________________________________________________________________________________________
tf.__operators__.add_323 (TFOpL (None, 80, 79)       0           dropout_336[0][0]
                                                                 input_13[0][0]
__________________________________________________________________________________________________
layer_normalization_313 (LayerN (None, 80, 79)       158         tf.__operators__.add_323[0][0]
__________________________________________________________________________________________________
conv1d_312 (Conv1D)             (None, 80, 1024)     81920       layer_normalization_313[0][0]
__________________________________________________________________________________________________
dropout_337 (Dropout)           (None, 80, 1024)     0           conv1d_312[0][0]
__________________________________________________________________________________________________
conv1d_313 (Conv1D)             (None, 80, 79)       80975       dropout_337[0][0]
__________________________________________________________________________________________________
tf.__operators__.add_324 (TFOpL (None, 80, 79)       0           conv1d_313[0][0]
                                                                 tf.__operators__.add_323[0][0]
__________________________________________________________________________________________________
layer_normalization_314 (LayerN (None, 80, 79)       158         tf.__operators__.add_324[0][0]
__________________________________________________________________________________________________
multi_head_attention_157 (Multi (None, 80, 79)       653391      layer_normalization_314[0][0]
                                                                 layer_normalization_314[0][0]
__________________________________________________________________________________________________
dropout_338 (Dropout)           (None, 80, 79)       0           multi_head_attention_157[0][0]
__________________________________________________________________________________________________
tf.__operators__.add_325 (TFOpL (None, 80, 79)       0           dropout_338[0][0]
                                                                 tf.__operators__.add_324[0][0]
__________________________________________________________________________________________________
layer_normalization_315 (LayerN (None, 80, 79)       158         tf.__operators__.add_325[0][0]
__________________________________________________________________________________________________
conv1d_314 (Conv1D)             (None, 80, 1024)     81920       layer_normalization_315[0][0]
__________________________________________________________________________________________________
dropout_339 (Dropout)           (None, 80, 1024)     0           conv1d_314[0][0]
__________________________________________________________________________________________________
conv1d_315 (Conv1D)             (None, 80, 79)       80975       dropout_339[0][0]
__________________________________________________________________________________________________
tf.__operators__.add_326 (TFOpL (None, 80, 79)       0           conv1d_315[0][0]
                                                                 tf.__operators__.add_325[0][0]
__________________________________________________________________________________________________
layer_normalization_316 (LayerN (None, 80, 79)       158         tf.__operators__.add_326[0][0]
__________________________________________________________________________________________________
multi_head_attention_158 (Multi (None, 80, 79)       653391      layer_normalization_316[0][0]
                                                                 layer_normalization_316[0][0]
__________________________________________________________________________________________________
dropout_340 (Dropout)           (None, 80, 79)       0           multi_head_attention_158[0][0]
__________________________________________________________________________________________________
tf.__operators__.add_327 (TFOpL (None, 80, 79)       0           dropout_340[0][0]
                                                                 tf.__operators__.add_326[0][0]
__________________________________________________________________________________________________
layer_normalization_317 (LayerN (None, 80, 79)       158         tf.__operators__.add_327[0][0]
__________________________________________________________________________________________________
conv1d_316 (Conv1D)             (None, 80, 1024)     81920       layer_normalization_317[0][0]
__________________________________________________________________________________________________
dropout_341 (Dropout)           (None, 80, 1024)     0           conv1d_316[0][0]
__________________________________________________________________________________________________
conv1d_317 (Conv1D)             (None, 80, 79)       80975       dropout_341[0][0]
__________________________________________________________________________________________________
tf.__operators__.add_328 (TFOpL (None, 80, 79)       0           conv1d_317[0][0]
                                                                 tf.__operators__.add_327[0][0]
__________________________________________________________________________________________________
layer_normalization_318 (LayerN (None, 80, 79)       158         tf.__operators__.add_328[0][0]
__________________________________________________________________________________________________
multi_head_attention_159 (Multi (None, 80, 79)       653391      layer_normalization_318[0][0]
                                                                 layer_normalization_318[0][0]
__________________________________________________________________________________________________
dropout_342 (Dropout)           (None, 80, 79)       0           multi_head_attention_159[0][0]
__________________________________________________________________________________________________
tf.__operators__.add_329 (TFOpL (None, 80, 79)       0           dropout_342[0][0]
                                                                 tf.__operators__.add_328[0][0]
__________________________________________________________________________________________________
layer_normalization_319 (LayerN (None, 80, 79)       158         tf.__operators__.add_329[0][0]
__________________________________________________________________________________________________
conv1d_318 (Conv1D)             (None, 80, 1024)     81920       layer_normalization_319[0][0]
__________________________________________________________________________________________________
dropout_343 (Dropout)           (None, 80, 1024)     0           conv1d_318[0][0]
__________________________________________________________________________________________________
conv1d_319 (Conv1D)             (None, 80, 79)       80975       dropout_343[0][0]
__________________________________________________________________________________________________
tf.__operators__.add_330 (TFOpL (None, 80, 79)       0           conv1d_319[0][0]
                                                                 tf.__operators__.add_329[0][0]
__________________________________________________________________________________________________
layer_normalization_320 (LayerN (None, 80, 79)       158         tf.__operators__.add_330[0][0]
__________________________________________________________________________________________________
multi_head_attention_160 (Multi (None, 80, 79)       653391      layer_normalization_320[0][0]
                                                                 layer_normalization_320[0][0]
__________________________________________________________________________________________________
dropout_344 (Dropout)           (None, 80, 79)       0           multi_head_attention_160[0][0]
__________________________________________________________________________________________________
tf.__operators__.add_331 (TFOpL (None, 80, 79)       0           dropout_344[0][0]
                                                                 tf.__operators__.add_330[0][0]
__________________________________________________________________________________________________
layer_normalization_321 (LayerN (None, 80, 79)       158         tf.__operators__.add_331[0][0]
__________________________________________________________________________________________________
conv1d_320 (Conv1D)             (None, 80, 1024)     81920       layer_normalization_321[0][0]
__________________________________________________________________________________________________
dropout_345 (Dropout)           (None, 80, 1024)     0           conv1d_320[0][0]
__________________________________________________________________________________________________
conv1d_321 (Conv1D)             (None, 80, 79)       80975       dropout_345[0][0]
__________________________________________________________________________________________________
tf.__operators__.add_332 (TFOpL (None, 80, 79)       0           conv1d_321[0][0]
                                                                 tf.__operators__.add_331[0][0]
__________________________________________________________________________________________________
layer_normalization_322 (LayerN (None, 80, 79)       158         tf.__operators__.add_332[0][0]
__________________________________________________________________________________________________
multi_head_attention_161 (Multi (None, 80, 79)       653391      layer_normalization_322[0][0]
                                                                 layer_normalization_322[0][0]
__________________________________________________________________________________________________
dropout_346 (Dropout)           (None, 80, 79)       0           multi_head_attention_161[0][0]
__________________________________________________________________________________________________
tf.__operators__.add_333 (TFOpL (None, 80, 79)       0           dropout_346[0][0]
                                                                 tf.__operators__.add_332[0][0]
__________________________________________________________________________________________________
layer_normalization_323 (LayerN (None, 80, 79)       158         tf.__operators__.add_333[0][0]
__________________________________________________________________________________________________
conv1d_322 (Conv1D)             (None, 80, 1024)     81920       layer_normalization_323[0][0]
__________________________________________________________________________________________________
dropout_347 (Dropout)           (None, 80, 1024)     0           conv1d_322[0][0]
__________________________________________________________________________________________________
conv1d_323 (Conv1D)             (None, 80, 79)       80975       dropout_347[0][0]
__________________________________________________________________________________________________
tf.__operators__.add_334 (TFOpL (None, 80, 79)       0           conv1d_323[0][0]
                                                                 tf.__operators__.add_333[0][0]
__________________________________________________________________________________________________
layer_normalization_324 (LayerN (None, 80, 79)       158         tf.__operators__.add_334[0][0]
__________________________________________________________________________________________________
multi_head_attention_162 (Multi (None, 80, 79)       653391      layer_normalization_324[0][0]
                                                                 layer_normalization_324[0][0]
__________________________________________________________________________________________________
dropout_348 (Dropout)           (None, 80, 79)       0           multi_head_attention_162[0][0]
__________________________________________________________________________________________________
tf.__operators__.add_335 (TFOpL (None, 80, 79)       0           dropout_348[0][0]
                                                                 tf.__operators__.add_334[0][0]
__________________________________________________________________________________________________
layer_normalization_325 (LayerN (None, 80, 79)       158         tf.__operators__.add_335[0][0]
__________________________________________________________________________________________________
conv1d_324 (Conv1D)             (None, 80, 1024)     81920       layer_normalization_325[0][0]
__________________________________________________________________________________________________
dropout_349 (Dropout)           (None, 80, 1024)     0           conv1d_324[0][0]
__________________________________________________________________________________________________
conv1d_325 (Conv1D)             (None, 80, 79)       80975       dropout_349[0][0]
__________________________________________________________________________________________________
tf.__operators__.add_336 (TFOpL (None, 80, 79)       0           conv1d_325[0][0]
                                                                 tf.__operators__.add_335[0][0]
__________________________________________________________________________________________________
layer_normalization_326 (LayerN (None, 80, 79)       158         tf.__operators__.add_336[0][0]
__________________________________________________________________________________________________
multi_head_attention_163 (Multi (None, 80, 79)       653391      layer_normalization_326[0][0]
                                                                 layer_normalization_326[0][0]
__________________________________________________________________________________________________
dropout_350 (Dropout)           (None, 80, 79)       0           multi_head_attention_163[0][0]
__________________________________________________________________________________________________
tf.__operators__.add_337 (TFOpL (None, 80, 79)       0           dropout_350[0][0]
                                                                 tf.__operators__.add_336[0][0]
__________________________________________________________________________________________________
layer_normalization_327 (LayerN (None, 80, 79)       158         tf.__operators__.add_337[0][0]
__________________________________________________________________________________________________
conv1d_326 (Conv1D)             (None, 80, 1024)     81920       layer_normalization_327[0][0]
__________________________________________________________________________________________________
dropout_351 (Dropout)           (None, 80, 1024)     0           conv1d_326[0][0]
__________________________________________________________________________________________________
conv1d_327 (Conv1D)             (None, 80, 79)       80975       dropout_351[0][0]
__________________________________________________________________________________________________
tf.__operators__.add_338 (TFOpL (None, 80, 79)       0           conv1d_327[0][0]
                                                                 tf.__operators__.add_337[0][0]
__________________________________________________________________________________________________
dense_35 (Dense)                (None, 80, 16)       1280        tf.__operators__.add_338[0][0]
__________________________________________________________________________________________________
dropout_352 (Dropout)           (None, 80, 16)       0           dense_35[0][0]
__________________________________________________________________________________________________
dense_36 (Dense)                (None, 80, 1)        17          dropout_352[0][0]
__________________________________________________________________________________________________
global_average_pooling1d_12 (Gl (None, 80)           0           tf.__operators__.add_338[0][0]
__________________________________________________________________________________________________
dropout_353 (Dropout)           (None, 80, 1)        0           dense_36[0][0]
__________________________________________________________________________________________________
tf.expand_dims_13 (TFOpLambda)  (None, 80, 1)        0           global_average_pooling1d_12[0][0]
__________________________________________________________________________________________________
tf.__operators__.add_339 (TFOpL (None, 80, 1)        0           dropout_353[0][0]
                                                                 tf.expand_dims_13[0][0]
__________________________________________________________________________________________________
dense_37 (Dense)                (None, 80, 1)        2           tf.__operators__.add_339[0][0]
==================================================================================================
Total params: 6,534,115
Trainable params: 6,534,115
Non-trainable params: 0
__________________________________________________________________________________________________
Epoch 1/300

Epoch 00001: LearningRateScheduler setting learning rate to tf.Tensor(0.001, shape=(), dtype=float32).
59/59 [==============================] - 90s 849ms/step - loss: 3.2324 - val_loss: 1.9128

Epoch 00001: val_loss improved from inf to 1.91284, saving model to folds0.hdf5
Epoch 2/300

Epoch 00002: LearningRateScheduler setting learning rate to tf.Tensor(0.000995129, shape=(), dtype=float32).
59/59 [==============================] - 9s 151ms/step - loss: 1.5616 - val_loss: 1.4432

Epoch 00002: val_loss improved from 1.91284 to 1.44317, saving model to folds0.hdf5
Epoch 3/300

Epoch 00003: LearningRateScheduler setting learning rate to tf.Tensor(0.0009902818, shape=(), dtype=float32).
31/59 [==============>...............] - ETA: 3s - loss: 1.2838

In [36]:
PRESSURE_STEP = 0.07030214545120961
PRESSURE_MIN = -1.8957442945646408
PRESSURE_MAX = 64.82099173863948

In [37]:
# ENSEMBLE FOLDS WITH MEAN
submission["pressure"] = sum(test_preds)/NUM_FOLDS
submission.to_csv('submission_mean.csv', index=False)

In [38]:
# ENSEMBLE FOLDS WITH MEDIAN
submission["pressure"] = np.median(np.vstack(test_preds),axis=0)
submission.to_csv('submission_median.csv', index=False)

In [39]:
# ENSEMBLE FOLDS WITH MEDIAN AND ROUND PREDICTIONS
submission["pressure"] =\
    np.round( (submission.pressure - PRESSURE_MIN)/PRESSURE_STEP ) * PRESSURE_STEP + PRESSURE_MIN
submission.pressure = np.clip(submission.pressure, PRESSURE_MIN, PRESSURE_MAX)
submission.to_csv('submission_median_round.csv', index=False)

In [40]:
!zip cnn_models.zip *.hdf5

  adding: folds0.hdf5 (deflated 9%)
  adding: folds1.hdf5 (deflated 9%)
  adding: folds2.hdf5 (deflated 9%)

In [41]:
!zip submission.zip *.csv

  adding: submission_mean.csv (deflated 62%)
  adding: submission_median.csv (deflated 60%)
  adding: submission_median_round.csv (deflated 80%)

In [42]:
with open('/gdrive/MyDrive/ventilator-pressure-prediction/submission.zip', 'wb') as f:
  f.write(open('submission.zip', 'rb').read())

In [43]:
with open('/gdrive/MyDrive/ventilator-pressure-prediction/cnn_models.zip', 'wb') as f:
  f.write(open('cnn_models.zip', 'rb').read())

In [44]:
!unzip -t /gdrive/MyDrive/ventilator-pressure-prediction/cnn_models.zip

Archive:  /gdrive/MyDrive/ventilator-pressure-prediction/cnn_models.zip
    testing: folds0.hdf5              OK
    testing: folds1.hdf5              OK
    testing: folds2.hdf5              OK
No errors detected in compressed data of /gdrive/MyDrive/ventilator-pressure-prediction/cnn_models.zip.